### ISSUE TITLE
UserDto setId() mission

### ISSUE THREAD

**Issue by Mfrenchy77** [ihorvitruk/buddysearch#2]
In Data module manager/impl AuthMangagerImpl you have saveUser(FirebaseUser user, Subscsriber<String> subscriber)

There you create a new UserDto and call setId.

The only set Id i found was from Entity, am I doing something wrong, the code won't compile for me?

Should there be getters and setters for the Dto?

**Comment by ihorvitruk** [comment]
Hello @Mfrenchy77 ! 
Thanks for your question. I use [Lombok](https://projectlombok.org/) library, and its annotation **@Data**. This annotation defines getters/setters, toString and other useful methods (See details on their site). 
Android Studio IDE does not compile your code, because you need to install Lombok Plugin.
For this, go to Preferences -> Plugins -> Browse Repositories and search for "Lombok plugin".
After you successfully plugin install and Android Studio restart , everything should work fine, compilation errors related to "getters/setters" should not occur.
